# GitHub Actions definition for CI build.

name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  WinBuildTest:
    name: Windows build and test
    runs-on: windows-2022  # 2019 is not sufficient, Windows 21H1+ is best for ReFS bug fixes
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        # No "with: dotnet-version" specified -> use global.json
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Enable Hyper-V for ReFS VHD testing
        # Hyper-V install wants to restart and pauses console, disable that.
        run: DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V /NoRestart
        shell: cmd
      #- name: See if VM reboot can work in CI pipeline
      #  run: shutdown -r -t 0
      #  shell: cmd
      # Broken - null object exception from Powershell
      #- name: Enable Hyper-V for ReFS VHD testing
      #  run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
      #  shell: pwsh
      - run: dotnet test --no-restore
