# GitHub Actions definition for CI build.

name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  WinBuildTest:
    name: Windows build and test
    runs-on: windows-2022  # 2019 is not sufficient, Windows 21H1+ is best for ReFS bug fixes
    steps:
      - run: |
          dir c:\
          dir d:\
          dir e:\
        shell: cmd
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        # No "with: dotnet-version" specified -> use global.json
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Enable Hyper-V for ReFS VHD testing
        # Hyper-V install wants to restart and pauses console, disable that.
        # Attempts to test VM reboot in GitHub Actions were not fruitful.
        # We would need Hyper-V baked into an image instead.
        run: |
          DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V /NoRestart
          if "%ERRORLEVEL%"=="3010" echo Expected 3010 exit code for pending reboot && exit /b 0
        shell: cmd
      - run: dotnet test --no-restore
